name: flutter_login_bloc
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'
dependencies:

  flutter:
    sdk: flutter
  bloc: ^8.1.0
  equatable: ^2.0.3
  flutter_bloc: ^8.1.1
  formz: ^0.6.0
  cupertino_icons: ^1.0.2
  user_repository:
    path: packages/user_repository
  authentication_repository:
    path: packages/authentication_repository


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  bloc_test: ^9.1.0
  mocktail: ^1.0.0

flutter:

  uses-material-design: true
